/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csmt;

import static csmt.MainMenu.sf;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 *@author Shubham
 */


public class LoginMain extends javax.swing.JFrame {
    
    static LoginMain lmf=null;
    static Connection conn=null;
    static PreparedStatement ps=null;
    static ResultSet rs=null;
    static int noOfItems;    
    
    public LoginMain() {
        
         try{
        Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
           JOptionPane.showMessageDialog(lmf,"COULD NOT CONNECT!","ERROR",JOptionPane.ERROR_MESSAGE);
           System.exit(0);
         }
        
        initComponents();
        setIcon();
    }
    
    
    public static boolean createDb(String pass) throws SQLException{
         try {
            //creating database csmtdb
           // System.out.println("CHECKing");
           // conn=DriverManager.getConnection("jdbc:mysql://Localhost/","root",pass);
           //System.out.println("create database csmtdb");
           String sq="create database csmthddb;";
           ps=conn.prepareStatement(sq);
           ps.executeUpdate();
           //System.out.println("use database csmtdb");
           sq="use csmthddb;";
           ps=conn.prepareStatement(sq);
           ps.executeUpdate();
           //System.out.println("create table csmtProductInfo");
           //sq="create table csmtProductInfo(pCode varchar(14) primary key,pName varchar(50) primary key,pStock int(9),pRate double(14,4),pEntryDate date,pExpiryDate date,pProfit double(5,2));";
           sq="create table csmtProductInfo(pCode varchar(14),pName varchar(50),pStock int(9),pRate double(14,4),pEntryDate date,pExpiryDate date,pProfit double(5,2), PRIMARY KEY(pCode,pName));";
           ps=conn.prepareStatement(sq);
           ps.executeUpdate();
           //System.out.println("create table csmtBill");
           sq="create table csmtBill(billCode varchar(12) primary key,billGenDate date,billAmt double(14,4));";
           ps=conn.prepareStatement(sq);
           ps.executeUpdate();
          // System.out.println("create table tempBill");
           sq="create table tempBill(sNo int(5) primary key,pCode varchar(14),pName varchar(30),pQty  int(9),pRate double(14,4));";
           ps=conn.prepareStatement(sq);
           ps.executeUpdate();
          // System.out.println("create table billInfo");
           sq="create table billInfo(billCode varchar(12),pCode varchar(14),pName varchar(30),pQty  int(9),pRate double(14,4) , Primary Key(billCode,pCode) );";
           ps=conn.prepareStatement(sq);
           ps.executeUpdate();
           
           sq="create table stockNsale(session varchar(10),pCode varchar(10),addStock int(9),sellStock int(9),purRate double(14,4),sellRate double(14,4), CONSTRAINT FOREIGN KEY(pCode) REFERENCES csmtproductinfo(pCode));";
           ps=conn.prepareStatement(sq);
           ps.executeUpdate();
           
           return true;
          
        }
        catch (SQLException ex) {
           //System.out.println("SQL CHECK: "+ex);
           return false;
        }
    }
    
    public static boolean checkConn(String pass) throws SQLException{
        try {
            Class.forName("com.mysql.jdbc.Driver");
           // System.out.println("CHECKing");
            conn=DriverManager.getConnection("jdbc:mysql://Localhost/","root",pass);
            
           String sq="show databases like 'csmthddb';";
           ps=conn.prepareStatement(sq);
           rs=ps.executeQuery();
           if(rs.next()){
               sq="use csmthddb;";
               ps=conn.prepareStatement(sq);
               ps.executeUpdate();
               return true;
           }
           else{
              return createDb(pass);
           }
              
          
          //  rs=ps.executeQuery();
           
        } catch (ClassNotFoundException ex) {
           //System.out.println("CLASS CHECK: "+ex);
            JOptionPane.showMessageDialog(lmf,"COULD NOT CONNECT!","ERROR",JOptionPane.ERROR_MESSAGE);
            System.exit(0);
            return false;
        }
        catch (SQLException ex) {
           //System.out.println("SQL CHECK: "+ex);
           return false;
        }
        
    }
  
    /** This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginUserName = new javax.swing.JTextField();
        loginPassword = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        loginErrorMsg = new javax.swing.JLabel();
        Clg_logo = new javax.swing.JLabel();
        BSF_logo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Login_Panel.setBackground(new java.awt.Color(204, 204, 204));
        Login_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2), "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        loginUserName.setEditable(false);
        loginUserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginUserName.setText("csmt");
        loginUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUserNameActionPerformed(evt);
            }
        });

        loginPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        loginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordActionPerformed(evt);
            }
        });

        loginBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        loginErrorMsg.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        loginErrorMsg.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout Login_PanelLayout = new javax.swing.GroupLayout(Login_Panel);
        Login_Panel.setLayout(Login_PanelLayout);
        Login_PanelLayout.setHorizontalGroup(
            Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Login_PanelLayout.createSequentialGroup()
                        .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Login_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginErrorMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(loginPassword)))
                            .addGroup(Login_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(loginUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)))
                .addContainerGap())
        );
        Login_PanelLayout.setVerticalGroup(
            Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Login_PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(loginUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginErrorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Clg_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CLG LOGO.png"))); // NOI18N

        BSF_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bsf logo.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scrollable-background-image.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 876, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BSF_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clg_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Login_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Clg_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BSF_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(68, 68, 68)
                        .addComponent(Login_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        
        String pass=String.valueOf(loginPassword.getPassword());
            String error1="<html><font color=red size=2>*required password!";
            String error2="<html><font color=red size=2>*wrong password!";
            if(pass.isEmpty()){
             loginErrorMsg.setText(error1);
            }else{
                try{
                if(checkConn(pass)){
                pass=null;   
                JOptionPane.showMessageDialog(null,"Login Successful");
                MainMenu sf=new MainMenu();
                lmf.setVisible(false);
                sf.setExtendedState(Frame.MAXIMIZED_BOTH);
                sf.setVisible(true);
                sf.setGraph();
             
                }else{
                    loginErrorMsg.setText(error2);
                   // JOptionPane.showMessageDialog(null,"You entered wrong password!","ERROR",JOptionPane.ERROR_MESSAGE);
                    //System.exit(0);
                }
                }catch(SQLException e){
                    System.out.println(e);
                }
            
            }// else
    
    }//GEN-LAST:event_loginBtnActionPerformed

    private void loginUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUserNameActionPerformed

    private void loginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordActionPerformed
        loginBtn.doClick();
    }//GEN-LAST:event_loginPasswordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                lmf=new LoginMain();
                lmf.loginPassword.requestFocusInWindow();
                lmf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BSF_logo;
    private javax.swing.JLabel Clg_logo;
    private javax.swing.JPanel Login_Panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginErrorMsg;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JTextField loginUserName;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        //getClass().getClassLoader().getResource("**resources/images/logo.png**"
        //java.net.URL url = ClassLoader.getSystemResource("com/xyz/resources/camera.png");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
